name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1]
        dependency-version: [prefer-stable]

    name: PHP ${{ matrix.php }} ${{ matrix.dependency-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: xdebug

    - name: Install PHP dependencies
      #run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-progress --ansi
      run: composer install --no-interaction

    - name: list
      run: ls -l && pwd 

    - name: pippo
      run: ls -l /home/runner/work/fortran-formatter/fortran-formatter/tests/

    - name: pippo2
      run: ls -l /home/runner/work/fortran-formatter/fortran-formatter/src/

    - name: Run Unit Tests
      run: vendor/bin/phpunit --verbose
